--USE OF ORDER BY AND NESTED ORDER BY

/*
--RETRIEVE ALL CUSTOMERS AND SORT RESULT BY THE LOWEST SCORE FIRST
SELECT *
FROM customers
ORDER BY score ASC


--RETRIEVE ALL CUSTOMERS AND SORT RESULT BY THE HIGHEST SCORE FIRST	
SELECT *
FROM customers
ORDER BY score DESC
*/

--NESTED ORDER BY
SELECT *
FROM customers
ORDER BY 
	country ASC,
	score DESC
	

