/*
-- USE OF HAVING

SELECT 
country,
SUM(score) AS total
FROM customers
WHERE score > 400  --FIRST CHECKS BASED ON WHERE. NORMAL SCORES > 400 WILL ONLY EXIST. filter data before aggregation
GROUP BY country
HAVING SUM(score) > 800 --SECONDLY CHECKS BASED ON SUN OF SCORE THAT IS GREATER THAN 800. filter data after aggregation
--HAVING IS ALWAYS USED WITH GROUP BY
*/

-- FIND THE AVERAGE SCORE FOR EACH COUNTRY 
-- CONSIDERING ONLY CUSTOMERS WITH A SCORE NOT EQUAL TO 0 
-- AND RETURN ONLY THOSE COUNTRIES WITH AN AVERAGE SCORE GREATER THAN 430
SELECT 
	id,
	country,
	score
FROM customers